<?php

// Имя поля ввода своей ТК.
define('GF_CUSTOM_OWN_CARGO_FIELD', 'ucxf_own_transport_company');
// HTML-элемент поля выбора ТК, при выборе которого будет видимым поле 
// ввода своей ТК.
define('GF_CUSTOM_OWN_CARGO_VISIBLE_JQ_ELEMENT', '#edit-panes-delivery-address-delivery-ucxf-cargo-company');
// Имя элемента списка выбора ТК, при выборе которого будет видимым поле 
// ввода своей ТК.
define('GF_CUSTOM_OWN_CARGO_VISIBLE_VAL', 'own_cargo');

/**
 * Implements hook_uc_addresses_address_fields_alter()
 *
 * Обрабатываем поля доставки транспортной компанией,
 * доступные при оформлении заказа.
 *
 */
function gf_custom_uc_addresses_address_field_alter(&$element) {
  // Обработка поля ввода своей трасп-й комп-и.
  if (isset($element[GF_CUSTOM_OWN_CARGO_FIELD])) {
    // Заголовок поля не нужен.
    $element[GF_CUSTOM_OWN_CARGO_FIELD]['#title'] = '';
    $condition = array(
      '#edit-panes-delivery-address-delivery-ucxf-cargo-company' => array(
        'value' => GF_CUSTOM_OWN_CARGO_VISIBLE_VAL
      ),
    );
    // Появлятся это полу будет только если покупатель выбрал
    // доставку своей ТК в соответствующем поле.
    $element[GF_CUSTOM_OWN_CARGO_FIELD]['#states'] = array(
            'visible' => $condition,
            'required' => $condition,
        );
  }
}

/**
 * Implements hook_uc_add_to_cart()
 */
function gf_custom_uc_add_to_cart($nid, $qty, $data) {
  $result = [];
  if (!user_access('create orders')) {
    // Запрещаем пользователям с отсутствием прав на создание заказов
    // добавлять товары в карзину.
    $result[] = array(
      'success' => FALSE,
      'message' => t('Sorry, you cannot create orders.'),
    );
  }
  return $result;
}

/**
 * Implements hook_uc_checkout_start()
 */
function gf_custom_uc_cart_checkout_start($order) {
  $account = user_load($order->uid);
  // Запрещаем пользователям с отсутствием прав на создание заказов эти
  // заказы создавать.
  if (!user_access('create orders', $account)) {
    drupal_set_message(t('Sorry, you cannot create orders.', 'error'));
    drupal_goto('cart');
  }
}


/**
 * Implements hook_form_FORM_ID_alter()
 *
 */
function gf_custom_form_user_register_form_alter(&$form, &$form_state) {
  global $language;
  $prefix = strtoupper($language->prefix);
  $country_options = &$form['field_country_name'][LANGUAGE_NONE]['#options'];
  $lang_pref_options = &$form['field_language_pref'][LANGUAGE_NONE]['#options'];
  if (isset($country_options[$prefix])) {
    $options = [];
    $options[$prefix] = $country_options[$prefix]; // текущий регион в самом вверху.
    // В списке выбора стран ставим Россию, Италию и Китай в начало списка.
    foreach (['RU', 'IT', 'CN'] as $key) {
      if ($key != $prefix) $options[$key] = $country_options[$key];
      unset($country_options[$key]);
    }
    $country_options = $options + $country_options;
    // В форме регистрации выбираем значение по-умолчанию для  поля "Страна" в
    // зависимости от языка пользователя.
    $form['field_country_name'][LANGUAGE_NONE]['#default_value'] = $prefix;
  }
  if (isset($lang_pref_options[$language->prefix])) {
    $form['field_language_pref'][LANGUAGE_NONE]['#default_value'] = $language->prefix;
  }
}

